# ================================
# .no1-service-tracker/secrets.toml (create this file locally & in your host's env)
# ================================
# DO NOT COMMIT REAL SECRETS TO GIT. Example only.
[supabase]
url = "https://kguwqtqmgdaijigcpjvi.supabase.co"
service_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndXdxdHFtZ2RhaWppZ2NwanZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTMwNDksImV4cCI6MjA3Mjc2OTA0OX0.nlDfWROvhS0tcDyC8fXrHZY-zaLEhHyuy7-rd_kJw_o" # service role, keep secret
#anon_key = "YOUR-SUPABASE-ANON-KEY" # optional; not required here


[app]
# Set the initial admin credentials for first run; the app will upsert this user.
bootstrap_admin_username = "admin"
bootstrap_admin_password = "ChangeMe_123!"

[cookies]
password = "really-long-random-secret"